[tool.poetry]
name = "linumpy"
version = "0.1.0"
description = "Tools and utilities to work with serial histology and microscopy data."
authors = ["Joël Lefebvre <lefebvre.joel@uqam.ca>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
SimpleITK = "^2.2.1"
numpy = "^1.24.3"
scipy = "^1.10.1"
imageio = "^2.28.1"
tqdm = "^4.65.0"
nibabel = "^3.2.2"
allensdk = "^2.15.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
pytest = "^7.3.1"
pytest-console-scripts = "^1.3.1"
pytest-cov = "^3.0.0"
coverage = "^6.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
