[tool.poetry]
name = "linumpy"
version = "0.1.0"
description = "Tools and utilities to work with serial histology and microscopy data."
authors = ["Joël Lefebvre <lefebvre.joel@uqam.ca>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
SimpleITK = "^2.1.1"
numpy = "^1.22.3"
scipy = "^1.8.0"
scikit-image = "^0.19.2"
imageio = "^2.19.1"
matplotlib = "^3.5.2"
tqdm = "^4.64.0"
nibabel = "^3.2.2"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
pytest = "^7.1.2"
pytest-console-scripts = "^1.3.1"
pytest-cov = "^3.0.0"
coverage = "^6.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
